//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercose4.WPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePair", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KeyValuePair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Exercose4.WPF.ServiceReference1.HelloWorldResponse HelloWorld(Exercose4.WPF.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Exercose4.WPF.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        double FahrenheitToCelsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        double CelsiusToFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius);
        
        // CODEGEN: Generating message contract since element name GetKeyValuePairsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeyValuePairs", ReplyAction="*")]
        Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponse GetKeyValuePairs(Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeyValuePairs", ReplyAction="*")]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponse> GetKeyValuePairsAsync(Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddKeyValuePair", ReplyAction="*")]
        Exercose4.WPF.ServiceReference1.AddKeyValuePairResponse AddKeyValuePair(Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddKeyValuePair", ReplyAction="*")]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.AddKeyValuePairResponse> AddKeyValuePairAsync(Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateResource", ReplyAction="*")]
        Exercose4.WPF.ServiceReference1.UpdateResourceResponse UpdateResource(Exercose4.WPF.ServiceReference1.UpdateResourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateResource", ReplyAction="*")]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.UpdateResourceResponse> UpdateResourceAsync(Exercose4.WPF.ServiceReference1.UpdateResourceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Exercose4.WPF.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Exercose4.WPF.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyValuePairsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyValuePairs", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequestBody Body;
        
        public GetKeyValuePairsRequest() {
        }
        
        public GetKeyValuePairsRequest(Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetKeyValuePairsRequestBody {
        
        public GetKeyValuePairsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyValuePairsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyValuePairsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponseBody Body;
        
        public GetKeyValuePairsResponse() {
        }
        
        public GetKeyValuePairsResponse(Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyValuePairsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exercose4.WPF.ServiceReference1.KeyValuePair[] GetKeyValuePairsResult;
        
        public GetKeyValuePairsResponseBody() {
        }
        
        public GetKeyValuePairsResponseBody(Exercose4.WPF.ServiceReference1.KeyValuePair[] GetKeyValuePairsResult) {
            this.GetKeyValuePairsResult = GetKeyValuePairsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddKeyValuePairRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddKeyValuePair", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.AddKeyValuePairRequestBody Body;
        
        public AddKeyValuePairRequest() {
        }
        
        public AddKeyValuePairRequest(Exercose4.WPF.ServiceReference1.AddKeyValuePairRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddKeyValuePairRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        public AddKeyValuePairRequestBody() {
        }
        
        public AddKeyValuePairRequestBody(string id, string value) {
            this.id = id;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddKeyValuePairResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddKeyValuePairResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.AddKeyValuePairResponseBody Body;
        
        public AddKeyValuePairResponse() {
        }
        
        public AddKeyValuePairResponse(Exercose4.WPF.ServiceReference1.AddKeyValuePairResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddKeyValuePairResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exercose4.WPF.ServiceReference1.KeyValuePair AddKeyValuePairResult;
        
        public AddKeyValuePairResponseBody() {
        }
        
        public AddKeyValuePairResponseBody(Exercose4.WPF.ServiceReference1.KeyValuePair AddKeyValuePairResult) {
            this.AddKeyValuePairResult = AddKeyValuePairResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResource", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.UpdateResourceRequestBody Body;
        
        public UpdateResourceRequest() {
        }
        
        public UpdateResourceRequest(Exercose4.WPF.ServiceReference1.UpdateResourceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResourceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isdel;
        
        public UpdateResourceRequestBody() {
        }
        
        public UpdateResourceRequestBody(string id, string value, bool isdel) {
            this.id = id;
            this.value = value;
            this.isdel = isdel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResourceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Exercose4.WPF.ServiceReference1.UpdateResourceResponseBody Body;
        
        public UpdateResourceResponse() {
        }
        
        public UpdateResourceResponse(Exercose4.WPF.ServiceReference1.UpdateResourceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResourceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Exercose4.WPF.ServiceReference1.KeyValuePair UpdateResourceResult;
        
        public UpdateResourceResponseBody() {
        }
        
        public UpdateResourceResponseBody(Exercose4.WPF.ServiceReference1.KeyValuePair UpdateResourceResult) {
            this.UpdateResourceResult = UpdateResourceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Exercose4.WPF.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Exercose4.WPF.ServiceReference1.WebServiceSoap>, Exercose4.WPF.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exercose4.WPF.ServiceReference1.HelloWorldResponse Exercose4.WPF.ServiceReference1.WebServiceSoap.HelloWorld(Exercose4.WPF.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Exercose4.WPF.ServiceReference1.HelloWorldRequest inValue = new Exercose4.WPF.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.HelloWorldRequestBody();
            Exercose4.WPF.ServiceReference1.HelloWorldResponse retVal = ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.HelloWorldResponse> Exercose4.WPF.ServiceReference1.WebServiceSoap.HelloWorldAsync(Exercose4.WPF.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Exercose4.WPF.ServiceReference1.HelloWorldRequest inValue = new Exercose4.WPF.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.HelloWorldRequestBody();
            return ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public double FahrenheitToCelsius(double fahrenheit) {
            return base.Channel.FahrenheitToCelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit) {
            return base.Channel.FahrenheitToCelsiusAsync(fahrenheit);
        }
        
        public double CelsiusToFahrenheit(double celsius) {
            return base.Channel.CelsiusToFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius) {
            return base.Channel.CelsiusToFahrenheitAsync(celsius);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponse Exercose4.WPF.ServiceReference1.WebServiceSoap.GetKeyValuePairs(Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest request) {
            return base.Channel.GetKeyValuePairs(request);
        }
        
        public Exercose4.WPF.ServiceReference1.KeyValuePair[] GetKeyValuePairs() {
            Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest inValue = new Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequestBody();
            Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponse retVal = ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).GetKeyValuePairs(inValue);
            return retVal.Body.GetKeyValuePairsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponse> Exercose4.WPF.ServiceReference1.WebServiceSoap.GetKeyValuePairsAsync(Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest request) {
            return base.Channel.GetKeyValuePairsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.GetKeyValuePairsResponse> GetKeyValuePairsAsync() {
            Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest inValue = new Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.GetKeyValuePairsRequestBody();
            return ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).GetKeyValuePairsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exercose4.WPF.ServiceReference1.AddKeyValuePairResponse Exercose4.WPF.ServiceReference1.WebServiceSoap.AddKeyValuePair(Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest request) {
            return base.Channel.AddKeyValuePair(request);
        }
        
        public Exercose4.WPF.ServiceReference1.KeyValuePair AddKeyValuePair(string id, string value) {
            Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest inValue = new Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.AddKeyValuePairRequestBody();
            inValue.Body.id = id;
            inValue.Body.value = value;
            Exercose4.WPF.ServiceReference1.AddKeyValuePairResponse retVal = ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).AddKeyValuePair(inValue);
            return retVal.Body.AddKeyValuePairResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.AddKeyValuePairResponse> Exercose4.WPF.ServiceReference1.WebServiceSoap.AddKeyValuePairAsync(Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest request) {
            return base.Channel.AddKeyValuePairAsync(request);
        }
        
        public System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.AddKeyValuePairResponse> AddKeyValuePairAsync(string id, string value) {
            Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest inValue = new Exercose4.WPF.ServiceReference1.AddKeyValuePairRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.AddKeyValuePairRequestBody();
            inValue.Body.id = id;
            inValue.Body.value = value;
            return ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).AddKeyValuePairAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Exercose4.WPF.ServiceReference1.UpdateResourceResponse Exercose4.WPF.ServiceReference1.WebServiceSoap.UpdateResource(Exercose4.WPF.ServiceReference1.UpdateResourceRequest request) {
            return base.Channel.UpdateResource(request);
        }
        
        public Exercose4.WPF.ServiceReference1.KeyValuePair UpdateResource(string id, string value, bool isdel) {
            Exercose4.WPF.ServiceReference1.UpdateResourceRequest inValue = new Exercose4.WPF.ServiceReference1.UpdateResourceRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.UpdateResourceRequestBody();
            inValue.Body.id = id;
            inValue.Body.value = value;
            inValue.Body.isdel = isdel;
            Exercose4.WPF.ServiceReference1.UpdateResourceResponse retVal = ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).UpdateResource(inValue);
            return retVal.Body.UpdateResourceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.UpdateResourceResponse> Exercose4.WPF.ServiceReference1.WebServiceSoap.UpdateResourceAsync(Exercose4.WPF.ServiceReference1.UpdateResourceRequest request) {
            return base.Channel.UpdateResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Exercose4.WPF.ServiceReference1.UpdateResourceResponse> UpdateResourceAsync(string id, string value, bool isdel) {
            Exercose4.WPF.ServiceReference1.UpdateResourceRequest inValue = new Exercose4.WPF.ServiceReference1.UpdateResourceRequest();
            inValue.Body = new Exercose4.WPF.ServiceReference1.UpdateResourceRequestBody();
            inValue.Body.id = id;
            inValue.Body.value = value;
            inValue.Body.isdel = isdel;
            return ((Exercose4.WPF.ServiceReference1.WebServiceSoap)(this)).UpdateResourceAsync(inValue);
        }
    }
}
